import 'bootstrap/dist/css/bootstrap.css';
import './globals.css';
import { Inter } from 'next/font/google';
import BootstrapClient from './components/BootstrapClient.js';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
    viewport: 'width=device-width, initial-scale=1',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>Event Sync</title>
            </head>
            <body>{children}</body>
        </html>
    );
}
